version: '3.4'

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
  
  collector:
    build:
      context: ./collector
    image: tweet-collector:0.1
    depends_on:
      - mongodb
    env_file: .env
    healthcheck:
      test: ['CMD', 'python', 'check.py']
      timeout: 10s
      retries: 2