resources:
  - type: compute.v1.instance
    name: twitter-collector
    properties:
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update && sudo apt-get install git -y
              sudo mkdir /collector
              sudo git clone https://github.com/fernandogbi/twitter-colector.git /collector
              curl -fsSL https://get.docker.com | sudo bash
              sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
              echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
              sudo apt-get update
              sudo apt-get install -y mongodb-org-shell
      zone: us-central1-a
      machineType: https://www.googleapis.com/compute/v1/projects/silicon-song-268520/zones/us-central1-a/machineTypes/g1-small
      disks:
        - deviceName: twitter-collector-boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/silicon-song-268520/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      
      