apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector: 
    matchLabels: 
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      restartPolicy: Always

      containers:
        - name: collector
          image: fernandogbi/twitter-collector:0.1.1
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: api-key

            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: api-secret-key

            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: access-token

            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: access-token-secret

              resources:
                limits:
                  memory: "300Mi"
                  cpu: "200m"





