apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector: 
    matchLabels: 
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      restartPolicy: Always

      containers:
        - name: mongo
          image: mongo:4.2
          ports:
            - containerPort: 27017

          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
      
  clusterIP: 10.96.0.2
  type: LoadBalancer
  externalIPs:
  - 10.0.0.218 #your internal ip




