apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always

      containers:
        - name: nginx
          image: matheusoliv/nginx-chart:0.1 
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: TZ
              value: America/Recife

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

  clusterIP: 10.96.0.6
  type: LoadBalancer
  externalIPs:
  - 172.42.42.100 #your internal ip
